name: 📝 Task 任务
description: Create a task for the team to work on 创建开发任务
title: "[Task]: "
labels: [Task]
body:
- type: textarea
  attributes:
    label: SubTasks 子任务
    placeholder: |
      - Sub Task 1
      - Sub Task 2
  validations:
    required: false
