blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help 问题咨询和讨论
    url: https://github.com/orgs/steedos/discussions
    about: Reach out to us github discussions page. 请访问 Github Discussions 页面
  - name: 📞 Contact us 联系我们
    url: https://console.steedos.cn/api/files/images/YRgRK94fwndMxMcjM
    about: 使用微信扫码加入开发者服务群，或是咨询商务问题。