version: "3.9"

services:
  steedos:
    image: ecr.aws.steedos.cn/dockerhub/steedos/steedos-enterprise:2.4.0-beta.8
    command: "yarn start"
    ports:
      - "5000:3000"
    volumes:   
      - "steedos-installed-packages:/app/.steedos"
      - "steedos-data:/app/storage"
    env_file:
      - .env.local
    environment:
      - MONGO_URL=mongodb://mongodb:27017/steedos2
      - MONGO_OPLOG_URL=mongodb://mongodb:27017/local
      - STEEDOS_CFS_STORE=local
      - STEEDOS_STORAGE_DIR=/app/storage
      - STEEDOS_TENANT_ENABLE_PASSWORD_LOGIN=true
      - TRANSPORTER=redis://redis:6379/2
      - CACHER=redis://redis:6379
      - STEEDOS_IDENTITY_JWT_ENABLED=true
      - STEEDOS_IDENTITY_JWT_SECRET=steedos
      - STEEDOS_IDENTITY_OIDC_ENABLED=true
      - STEEDOS_IDENTITY_OIDC_CONFIG_URL=https://id.steedos.cn/realms/master/.well-known/openid-configuration
      - STEEDOS_IDENTITY_OIDC_CLIENT_ID=steedos-oidc-public
      - STEEDOS_IDENTITY_OIDC_CLIENT_SECRET=none
      - STEEDOS_IDENTITY_OIDC_NAME=Steedos ID
      - STEEDOS_INITIAL_PACKAGES="@steedos-labs/project-ee,@steedos-labs/demo-ee"
      - STEEDOS_BUILDER_URL=https://beta.builder.steedos.com
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 60s
      timeout: 10s
      retries: 3
    depends_on:
      redis:
        condition: service_started
      mongodb:
        condition: service_healthy
    
  redis:
    image: ecr.aws.steedos.cn/dockerhub/bitnami/redis:6.2
    command: "redis-server --save \"\" --appendonly no --loglevel warning"
    ports:
      - "6379:6379"
  

  mongodb:
    image: ecr.aws.steedos.cn/dockerhub/bitnami/mongodb:4.4
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb
      - MONGODB_REPLICA_SET_NAME=steedos
      - MONGODB_ENABLE_JOURNAL=true
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: echo 'rs.status().ok' | mongo steedos --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - 'steedos-mongo-data:/bitnami'


volumes:
  steedos-mongo-data:
  steedos-installed-packages:
  steedos-data: